imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# FOSRestBundle
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: "force"
        force_redirects:
            html: false
        formats:
            json:  true
            jsonp: true
            xml:   true
        templating_formats:
            html: true
        jsonp_handler: ~
        default_engine: twig
    exception:
        codes:
            "Symfony\Component\Routing\Exception\ResourceNotFoundException": 404
            "Doctrine\ORM\OptimisticLockException": HTTP_CONFLICT
    routing_loader:
        default_format: json


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

vich_uploader:
    db_driver: orm

    mappings:
            achievement_image:
                uri_prefix:         /images/achievements
                upload_destination: %kernel.root_dir%/../web/images/achievements
                namer:              vich_uploader.namer_uniqid
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            user_image:
                uri_prefix:         /images/users
                upload_destination: %kernel.root_dir%/../web/images/users
                namer:              vich_uploader.namer_uniqid
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            report_image:
                uri_prefix:         /images/reports
                upload_destination: %kernel.root_dir%/../web/images/reports
                namer:              vich_uploader.namer_uniqid
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

nelmio_api_doc:
    name: "Trashcam API documentation"
    sandbox:
        accept_type: application/json

# Nelmio CorsBundle
nelmio_cors:
        paths:
            '^/api/':
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']