<?php

namespace AppBundle\Repository;

/**
 * AchievementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementsRepository extends \Doctrine\ORM\EntityRepository
{
}
