users:
    resource: ApiBundle\Controller\UserController
    type: rest

#reports:
#    resource: ApiBundle\Controller\ReportsController
#    type: rest
#
achievements:
    resource: ApiBundle\Controller\AchievementController
    type: rest

#status:
#    resource: ApiBundle\Controller\StatusController
#    type: rest